{
 "title": "AWS ALB VFQ-PROD",
 "description": "Visualize AWS ELB Application Load Balancer and Target Group metrics",
 "tags": [
  "cloudwatch",
  "alb",
  "aws"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "eu-west-1" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": {}
   },
   {
    "name": "targetgroup",
    "label": "Target Group",
    "query": "dimension_values($region,AWS/ApplicationELB,HealthyHostCount,TargetGroup, {\"LoadBalancer\":\"$loadbalancername\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "All UnHealthy TargetGroups ($loadbalancername)",
   "type": "bargauge",
   "description": "The number of targets that are considered unhealthy.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "*" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Healthy Hosts ($targetgroup)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts ($targetgroup)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Avg. TargetResponseTime ($targetgroup)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Avg TargetConnectionErrors ($targetgroup)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ELB and TargetGroup Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RequestCount / TargetResponseTime ($loadbalancername)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RequestCount / TargetResponseTime ($targetgroup)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HTTPCode_Target ($loadbalancername)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode_Target ($targetgroup)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode_ELB ($loadbalancername)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode_TargetGroup ($targetgroup)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ELB Only Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ConnectionCount (ELB Only)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RejectedConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ConsumedLBCapacityUnits / ConsumedLCUs / ProcessedBytes (ELB Only)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConsumedLBCapacityUnits",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TLSNegotiationErrorCount (ELB Only)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TargetTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClientTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "RuleEvaluations (ELB Only)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RuleEvaluations",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Auth (ELB Only)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthFailure",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthSuccess",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthRefreshTokenSuccess",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthUserClaimsSizeExceeded",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthLatency",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}