{
 "title": "AWS WAFv2 Stats - example",
 "description": "Dashboard with statistics from AWS WAFv2 via CloudWatch Logs Insights queries",
 "tags": [
  "aws",
  "waf",
  "wafv2",
  "cloudwatch"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   { "name": "region", "query": "eu-west-1" },
   {
    "name": "log_group",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message |\n stats count(*) as total",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "expression": "fields action |\n filter action like \"BLOCK\" |\n stats count(*) as blocked",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Requests by Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "fields httpRequest.country |\n stats count(*) as num_requests by httpRequest.country",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average",
     "statsGroups": [ "httpRequest.country" ]
    }
   ]
  },
  {
   "title": "Requests by Country",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expression": "fields httpRequest.country |\n stats count(*) as num_requests by httpRequest.country",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average",
     "statsGroups": [ "httpRequest.country" ]
    }
   ]
  },
  {
   "title": "Requests by Country",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expression": "fields httpRequest.country |\n stats count(*) as num_requests by httpRequest.country",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average",
     "statsGroups": [ "httpRequest.country" ]
    }
   ]
  },
  { "title": "Top 10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Client IPs",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "fields httpRequest.clientIp\n| stats count(*) as requestCount by httpRequest.clientIp\n| sort requestCount desc\n| limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average",
     "statsGroups": [ "httpRequest.clientIp" ]
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse @message '{\"name\":\"User-Agent\",\"value\":\"*\"}' as userAgent\n| stats count(*) as requestCount by userAgent\n| sort requestCount desc\n| limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average",
     "statsGroups": [ "userAgent" ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse @message '{\"name\":\"Host\",\"value\":\"*\"}' as host\n| stats count(*) as requestCount by host\n| sort requestCount desc\n| limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average",
     "statsGroups": [ "host" ]
    }
   ]
  },
  {
   "title": "Terminating Rule",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields terminatingRuleId |\n  stats count(*) as num by terminatingRuleId |\n  limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average",
     "statsGroups": [ "terminatingRuleId" ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "BLOCK Actions - HTTP Request",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expression": "fields @message\n| filter action = \"BLOCK\"",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ALL Actions - HTTP Request",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expression": "fields @message",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}