---
# helm repo add aws-secrets-manager https://aws.github.io/secrets-store-csi-driver-provider-aws
# helm repo update aws-secrets-manager
# helm upgrade --install -n kube-system secrets-provider-aws aws-secrets-manager/secrets-store-csi-driver-provider-aws -f secrets-provider-aws.yaml --version 0.3.2 --dry-run --debug

# Values for secrets-store-csi-driver-provider-aws
# needs to be changed from default to create pods on all nodes
tolerations:
  - operator: Exists
resources:
  requests:
    cpu: 50m
    memory: 20Mi
  limits:
    cpu: 200m
    memory: 90M
...