---
# helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
# helm repo update secrets-store-csi-driver
# helm upgrade --install -n kube-system csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver -f secrets-store-csi-driver.yaml --version 1.3.2 --dry-run --debug

# Only those parameters which have been changed from default

## Install RBAC roles and bindings required for K8S Secrets syncing if true
syncSecret:
  enabled: true

## Enable secret rotation feature [alpha]
enableSecretRotation: true

## Secret rotation poll interval duration (default is 2m)
# rotationPollInterval: 2m

linux:
  driver:
    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 30Mi
  registrar:
    resources:
      limits:
        cpu: 300m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10Mi
  livenessProbe:
    resources:
      limits:
        cpu: 300m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10Mi
...