---
# Example Application Found New Log Alert
# This alert is used to monitor the Example Application found new log.
# These alerts are not part of the default rules and are added to the PrometheusRule object.
## kubectl apply -n infrastructure -f example-application-foundnewlog.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    grafana_alert: "1"
  name: alert-production-example-application-found-new-log
  namespace: infrastructure
data:
  rules.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: production-Example-Application-FoundNewLog
          folder: example-application-alerts
          interval: 1m
          rules:
            - uid: b19a9e41-fe75-499a-b26b-6ba319504a00
              title: production-Example-Application-FoundNewLog
              condition: C
              data:
                - refId: A
                  queryType: range
                  relativeTimeRange:
                    from: 3600
                    to: 0
                  datasourceUid: P982945308D3682D1
                  model:
                    datasource:
                        type: loki
                        uid: P982945308D3682D1
                    editorMode: code
                    expr: 'sum(count_over_time({app="example-application", namespace="production"} |= "error" [5m])) by (app)'
                    intervalMs: 1000
                    key: Q-0685966c-4a46-4cc5-954e-db4c2d406a81-0
                    legendFormat: ""
                    maxDataPoints: 43200
                    queryType: range
                    refId: A
                - refId: B
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params: []
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - B
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    reducer: last
                    refId: B
                    type: reduce
                - refId: C
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: B
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              dashboardUid: exampleapplicationfoundnewlog
              panelId: 2
              noDataState: OK
              execErrState: Error
              for: 1m
              annotations:
                __dashboardUid__: exampleapplicationfoundnewlog
                __panelId__: "2"
                summary: production Example Application Found Out New Not Known Error Logs!!
              labels:
                app: example-application
                environment: production
                namespace: production
                statuscode: none
                team: developers
              isPaused: false
...